version: "3.6"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:80
        env_file:
            - ./.env.template
        restart: unless-stopped